"""adjusting table 'students'

Revision ID: 4b81184f715c
Revises: 16511c066f73
Create Date: 2022-01-06 14:43:58.026815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b81184f715c'
down_revision = '16511c066f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('grade', sa.String(length=20), nullable=False))
    op.add_column('students', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_constraint('students_phone_key', 'students', type_='unique')
    op.create_unique_constraint(None, 'students', ['email'])
    op.drop_column('students', 'created_at')
    op.drop_column('students', 'full_name')
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.VARCHAR(length=14), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='unique')
    op.create_unique_constraint('students_phone_key', 'students', ['phone'])
    op.drop_column('students', 'password_hash')
    op.drop_column('students', 'email')
    op.drop_column('students', 'grade')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'name')
    # ### end Alembic commands ###
